# Generated by Django 3.0.5 on 2021-02-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210219_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='thumnail',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
